/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.dashboard;

import component.NavBarSample;
import function.NavigationManager;
import gui.table.*;
import java.awt.BorderLayout;

/**
 *
 * @author Kang Wei
 */
public class AdminDashBoard extends javax.swing.JFrame {
    /**
     * Creates new form DashBoardSample
     */
    private int currentPage = 1; // Track current page
    
    public AdminDashBoard() {
        initComponents();
        this.setLocationRelativeTo(null); //this will center your frame
        
        // Create and add navbar
        NavBarSample navbar = new NavBarSample();
        jPanel1.add(navbar, BorderLayout.NORTH); // Add to top
        
        // Initial state
        page1.setVisible(true);
        page2.setVisible(false);
        PrevPageButton.setEnabled(false); // Disable previous button initially

    }
    
    // Custom Methods
    private void showPage(int pageNumber) {
        // Switch page visibility
        if (pageNumber == 1) {
            page1.setVisible(true);
            page2.setVisible(false);
        } else {
            page1.setVisible(false);
            page2.setVisible(true);
        }

        // Update navigation button states
        PrevPageButton.setEnabled(pageNumber != 1);  // Disable on first page
        nextPageButton.setEnabled(pageNumber != 2);  // Disable on last page

        currentPage = pageNumber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navBarSample1 = new component.NavBarSample();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pages = new javax.swing.JPanel();
        page1 = new javax.swing.JPanel();
        purchaseRequisitionBtn = new javax.swing.JButton();
        paymentBtn = new javax.swing.JButton();
        supplierBtn = new javax.swing.JButton();
        purchaseOrderBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        dailySalesBtn = new javax.swing.JButton();
        page2 = new javax.swing.JPanel();
        stockUpdateBtn = new javax.swing.JButton();
        itemBtn = new javax.swing.JButton();
        financialReportBtn = new javax.swing.JButton();
        StockReportBtn = new javax.swing.JButton();
        nextPageButton = new javax.swing.JButton();
        PrevPageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().add(navBarSample1, java.awt.BorderLayout.PAGE_START);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Dashboard");
        jLabel1.setToolTipText("");

        pages.setLayout(new java.awt.CardLayout());

        purchaseRequisitionBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        purchaseRequisitionBtn.setText("Purchase Requisition");
        purchaseRequisitionBtn.setBorderPainted(false);
        purchaseRequisitionBtn.setMargin(new java.awt.Insets(2, 0, 3, 0));
        purchaseRequisitionBtn.setPreferredSize(new java.awt.Dimension(150, 100));
        purchaseRequisitionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseRequisitionBtnActionPerformed(evt);
            }
        });

        paymentBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paymentBtn.setText("Payment");
        paymentBtn.setBorderPainted(false);
        paymentBtn.setPreferredSize(new java.awt.Dimension(150, 100));
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });

        supplierBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        supplierBtn.setText("Supplier");
        supplierBtn.setBorderPainted(false);
        supplierBtn.setPreferredSize(new java.awt.Dimension(150, 100));
        supplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBtnActionPerformed(evt);
            }
        });

        purchaseOrderBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        purchaseOrderBtn.setText("Purchase Order");
        purchaseOrderBtn.setBorderPainted(false);
        purchaseOrderBtn.setMargin(new java.awt.Insets(2, 0, 3, 0));
        purchaseOrderBtn.setPreferredSize(new java.awt.Dimension(150, 100));
        purchaseOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseOrderBtnActionPerformed(evt);
            }
        });

        userBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userBtn.setText("User");
        userBtn.setBorderPainted(false);
        userBtn.setPreferredSize(new java.awt.Dimension(150, 100));
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });

        dailySalesBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dailySalesBtn.setText("Daily Sales");
        dailySalesBtn.setBorderPainted(false);
        dailySalesBtn.setPreferredSize(new java.awt.Dimension(150, 100));
        dailySalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailySalesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout page1Layout = new javax.swing.GroupLayout(page1);
        page1.setLayout(page1Layout);
        page1Layout.setHorizontalGroup(
            page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page1Layout.createSequentialGroup()
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(page1Layout.createSequentialGroup()
                        .addComponent(supplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(dailySalesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(page1Layout.createSequentialGroup()
                        .addComponent(userBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchaseRequisitionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purchaseOrderBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        page1Layout.setVerticalGroup(
            page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page1Layout.createSequentialGroup()
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseRequisitionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailySalesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pages.add(page1, "card3");

        stockUpdateBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stockUpdateBtn.setText("Stock Update");
        stockUpdateBtn.setBorderPainted(false);
        stockUpdateBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stockUpdateBtn.setInheritsPopupMenu(true);
        stockUpdateBtn.setPreferredSize(new java.awt.Dimension(150, 100));
        stockUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockUpdateBtnActionPerformed(evt);
            }
        });

        itemBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemBtn.setText("Item");
        itemBtn.setBorderPainted(false);
        itemBtn.setPreferredSize(new java.awt.Dimension(150, 100));
        itemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBtnActionPerformed(evt);
            }
        });

        financialReportBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        financialReportBtn.setText("Financial Report");
        financialReportBtn.setBorderPainted(false);
        financialReportBtn.setMargin(new java.awt.Insets(2, 0, 3, 0));
        financialReportBtn.setPreferredSize(new java.awt.Dimension(150, 100));
        financialReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financialReportBtnActionPerformed(evt);
            }
        });

        StockReportBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StockReportBtn.setText("Stock Report");
        StockReportBtn.setBorderPainted(false);
        StockReportBtn.setMargin(new java.awt.Insets(2, 0, 3, 0));
        StockReportBtn.setPreferredSize(new java.awt.Dimension(150, 100));
        StockReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout page2Layout = new javax.swing.GroupLayout(page2);
        page2.setLayout(page2Layout);
        page2Layout.setHorizontalGroup(
            page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page2Layout.createSequentialGroup()
                .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(page2Layout.createSequentialGroup()
                        .addComponent(itemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(stockUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(page2Layout.createSequentialGroup()
                        .addComponent(StockReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50)
                .addComponent(financialReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        page2Layout.setVerticalGroup(
            page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page2Layout.createSequentialGroup()
                .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stockUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(itemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(financialReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(StockReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pages.add(page2, "card3");

        nextPageButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nextPageButton.setText(">");
        nextPageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextPageButton.setPreferredSize(new java.awt.Dimension(50, 50));
        nextPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPageButtonMouseClicked(evt);
            }
        });

        PrevPageButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PrevPageButton.setText("<");
        PrevPageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PrevPageButton.setPreferredSize(new java.awt.Dimension(50, 50));
        PrevPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrevPageButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(PrevPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(nextPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(pages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrevPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextPageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPageButtonMouseClicked
        showPage(2);
    }//GEN-LAST:event_nextPageButtonMouseClicked

    private void PrevPageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrevPageButtonMouseClicked
        showPage(1);
    }//GEN-LAST:event_PrevPageButtonMouseClicked

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        // TODO add your handling code here:
        NavigationManager.getInstance().openFrame(new UserTable(), this);
    }//GEN-LAST:event_userBtnActionPerformed

    private void purchaseRequisitionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseRequisitionBtnActionPerformed
        // TODO add your handling code here:
        NavigationManager.getInstance().openFrame(new PurchaseRequsitionTable(), this);
    }//GEN-LAST:event_purchaseRequisitionBtnActionPerformed

    private void purchaseOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseOrderBtnActionPerformed
        // TODO add your handling code here:
        NavigationManager.getInstance().openFrame(new PurchaseOrderTable(), this);
    }//GEN-LAST:event_purchaseOrderBtnActionPerformed

    private void supplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBtnActionPerformed
        // TODO add your handling code here:
        NavigationManager.getInstance().openFrame(new SupplierTable(), this);
    }//GEN-LAST:event_supplierBtnActionPerformed

    private void dailySalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailySalesBtnActionPerformed
        // TODO add your handling code here:
        NavigationManager.getInstance().openFrame(new DailySaleTable(), this);
    }//GEN-LAST:event_dailySalesBtnActionPerformed

    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        // TODO add your handling code here:
        NavigationManager.getInstance().openFrame(new PaymentTable(), this);
    }//GEN-LAST:event_paymentBtnActionPerformed

    private void itemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBtnActionPerformed
        // TODO add your handling code here:
        NavigationManager.getInstance().openFrame(new ItemTable(), this);
    }//GEN-LAST:event_itemBtnActionPerformed

    private void stockUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockUpdateBtnActionPerformed
        // TODO add your handling code here:
        NavigationManager.getInstance().openFrame(new StockUpdateTable(), this);
    }//GEN-LAST:event_stockUpdateBtnActionPerformed

    private void financialReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financialReportBtnActionPerformed
        // TODO add your handling code here:
        NavigationManager.getInstance().openFrame(new FinancialReportTable(), this);
    }//GEN-LAST:event_financialReportBtnActionPerformed

    private void StockReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockReportBtnActionPerformed
        // TODO add your handling code here:
        NavigationManager.getInstance().openFrame(new StockReportTable(), this);
    }//GEN-LAST:event_StockReportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrevPageButton;
    private javax.swing.JButton StockReportBtn;
    private javax.swing.JButton dailySalesBtn;
    private javax.swing.JButton financialReportBtn;
    private javax.swing.JButton itemBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private component.NavBarSample navBarSample1;
    private javax.swing.JButton nextPageButton;
    private javax.swing.JPanel page1;
    private javax.swing.JPanel page2;
    private javax.swing.JPanel pages;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JButton purchaseOrderBtn;
    private javax.swing.JButton purchaseRequisitionBtn;
    private javax.swing.JButton stockUpdateBtn;
    private javax.swing.JButton supplierBtn;
    private javax.swing.JButton userBtn;
    // End of variables declaration//GEN-END:variables
}
